=== PoussinElitiste/CodeSample/XML Sample/peopleDTD.dtd
<!ELEMENT people (husband)*>
<!ATTLIST husband employed CDATA "yes">
<!ELEMENT husband (name,age,wife)>
<!ELEMENT name (#PCDATA)*>
<!ELEMENT age (#PCDATA)*>
<!ELEMENT wife (wname,age)>
<!ELEMENT wname (#PCDATA)*>

=== PoussinElitiste/CodeSample/XML Sample/people.xml
<?xml version="1.0" standalone="no" ?>

<!DOCTYPE people SYSTEM "peopleDTD.dtd">
<?xml-stylesheet type="text/css" href="peopleCSS.css"?>
<!-- <?xml-stylesheet type="text/xsl" href="people.xsl"?> -->


<people>
	<husband class="one" employed="yes">
		<name>Mark</name>
		<age>45</age>
		<wife>
			<wname>Janet</wname>
			<age>29</age>
		</wife>
	</husband>
	<husband class="two" employed="no">
		<name>Matt</name>
		<age>42</age>
		<wife>
			<wname>Annie</wname>
			<age>43</age>
		</wife>
	</husband>
	<husband class="two" employed="no">
		<name>Bob</name>
		<age>46</age>
		<wife>
			<wname>Agnes</wname>
			<age>41</age>
		</wife>
	</husband>
</people>
